# backend/app/services/advisory_rules.py
"""
Rule-based maternal advisory engine (single source of truth for thresholds).

This module is PURE: no database, no settings, no network. It takes the
*latest recorded value per (section, factor)* and returns deterministic,
explainable flags, an overall risk level, advisory actions and a referral
suggestion.

Both public engines build on `evaluate_latest_values`:
- `app.services.risk_engine.RiskEngine`      -> POST /ai/risk
- `app.services.ai_patient_service`          -> /ai-analysis/* (frontend cards)

Section / factor keys are the ones defined in `app.models.medical_schema`
(`MEDICAL_SCHEMA`). Do not read keys that the schema does not define.

Vocabulary (stable; the frontend depends on these values):
- risk level : unknown | low | medium | high | critical
- urgency    : low | medium | high | critical
- severity   : info | warning | severe | critical   (per flag)

Nothing here is a diagnosis. Every string is advisory and is checked with
`app.ai.validators.validate_advisory_language`.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

from app.ai.validators import validate_advisory_language

# ---------------------------------------------------------------------------
# Constants / vocabularies
# ---------------------------------------------------------------------------

ENGINE_VERSION = "rule-based-advisory-v2"

RISK_UNKNOWN = "unknown"
RISK_LOW = "low"
RISK_MEDIUM = "medium"
RISK_HIGH = "high"
RISK_CRITICAL = "critical"
RISK_LEVELS: Tuple[str, ...] = (RISK_UNKNOWN, RISK_LOW, RISK_MEDIUM, RISK_HIGH, RISK_CRITICAL)

URGENCY_LOW = "low"
URGENCY_MEDIUM = "medium"
URGENCY_HIGH = "high"
URGENCY_CRITICAL = "critical"
URGENCY_LEVELS: Tuple[str, ...] = (URGENCY_LOW, URGENCY_MEDIUM, URGENCY_HIGH, URGENCY_CRITICAL)

SEV_INFO = "info"
SEV_WARNING = "warning"
SEV_SEVERE = "severe"
SEV_CRITICAL = "critical"
_SEV_RANK = {SEV_INFO: 0, SEV_WARNING: 1, SEV_SEVERE: 2, SEV_CRITICAL: 3}

DOMAIN_MATERNAL = "maternal"
DOMAIN_FETAL = "fetal"
DOMAIN_HISTORY = "history"

DISCLAIMER = (
    "This output is generated by a deterministic rule-based advisory engine "
    f"({ENGINE_VERSION}) from the latest recorded values only. It is advisory, "
    "is not a diagnosis, and does not replace clinical assessment. Clinical "
    "decisions rest with the responsible qualified clinician."
)

# Referral score cap (sum of rule weights, capped). Kept for continuity with the
# previous UI which shows this number as a percentage.
REFERRAL_SCORE_CAP = 0.95

# ---------------------------------------------------------------------------
# Input keys (section, factor) -- exactly as stored by the medical schema
# ---------------------------------------------------------------------------

K_BP_SYS = ("vitals", "blood_pressure_systolic")
K_BP_DIA = ("vitals", "blood_pressure_diastolic")
K_PULSE = ("vitals", "pulse_rate")  # MATERNAL pulse only
K_TEMP = ("vitals", "temperature")
K_RR = ("vitals", "respiratory_rate")
K_BMI = ("vitals", "body_mass_index")

K_HB = ("blood_investigations", "hemoglobin")
K_GLUCOSE = ("blood_investigations", "blood_glucose")
K_PLATELETS = ("blood_investigations", "platelet_count")

K_DIPSTICK = ("urine_examination", "dipstick_protein")
K_PROTEIN_24H = ("urine_examination", "urine_protein_24hr")
K_PCR = ("urine_examination", "protein_creatinine_ratio")

K_FHR_ABDO = ("per_abdominal_examination", "fetal_heart_rate")
K_FHR_USG = ("ultrasonography", "fetal_heart_rate")
K_PLACENTA = ("ultrasonography", "placental_location")

K_SYMPTOMS_T2 = ("second_trimester_anc", "headache_epigastric_visual_symptoms")
K_SYMPTOMS_T3 = ("third_trimester_anc", "headache_epigastric_visual_symptoms")
K_BLEED_T1 = ("first_trimester_anc", "vaginal_bleeding_or_discharge")
K_BLEED_T3 = ("third_trimester_anc", "vaginal_bleeding_or_discharge")
K_FEVER_URI_T1 = ("first_trimester_anc", "fever_or_urinary_symptoms")
K_FEVER_URI_T2 = ("second_trimester_anc", "fever_or_urinary_symptoms")
K_FEVER_URI_T3 = ("third_trimester_anc", "fever_or_urinary_symptoms")
K_FETAL_MOVEMENT_T3 = ("third_trimester_anc", "fetal_movement_normal")

K_PALLOR = ("general_signs", "pallor")
K_EDEMA = ("general_signs", "edema")
K_CONSCIOUSNESS = ("general_examination", "level_of_consciousness")

K_HX_HTN = ("past_medical_history", "hypertension")
K_HX_DM = ("past_medical_history", "diabetes")
K_HX_LOSS = ("obstetric_history", "pregnancy_loss_history")
K_HX_COMPLICATIONS = ("obstetric_history", "previous_complications")

# Groups where the same clinical meaning is captured in several sections; the
# most recent recorded value across the group is used.
GROUP_SYMPTOMS: Tuple[Tuple[str, str], ...] = (K_SYMPTOMS_T2, K_SYMPTOMS_T3)
GROUP_BLEEDING: Tuple[Tuple[str, str], ...] = (K_BLEED_T1, K_BLEED_T3)
GROUP_FEVER_URINARY: Tuple[Tuple[str, str], ...] = (K_FEVER_URI_T1, K_FEVER_URI_T2, K_FEVER_URI_T3)
GROUP_FHR: Tuple[Tuple[str, str], ...] = (K_FHR_ABDO, K_FHR_USG)

# Every key the engine reads (used to decide "unknown" = no evaluable data).
RULE_INPUT_KEYS: Tuple[Tuple[str, str], ...] = (
    K_BP_SYS, K_BP_DIA, K_PULSE, K_TEMP, K_RR, K_BMI,
    K_HB, K_GLUCOSE, K_PLATELETS,
    K_DIPSTICK, K_PROTEIN_24H, K_PCR,
    K_FHR_ABDO, K_FHR_USG, K_PLACENTA,
    K_SYMPTOMS_T2, K_SYMPTOMS_T3, K_BLEED_T1, K_BLEED_T3,
    K_FEVER_URI_T1, K_FEVER_URI_T2, K_FEVER_URI_T3, K_FETAL_MOVEMENT_T3,
    K_PALLOR, K_EDEMA, K_CONSCIOUSNESS,
    K_HX_HTN, K_HX_DM, K_HX_LOSS, K_HX_COMPLICATIONS,
)

# ---------------------------------------------------------------------------
# Thresholds (single place to tune). Units follow the medical schema.
# ---------------------------------------------------------------------------

THRESHOLDS: Dict[str, Any] = {
    # Blood pressure (mmHg)
    "bp_systolic_elevated": 140,
    "bp_diastolic_elevated": 90,
    "bp_systolic_severe": 160,
    "bp_diastolic_severe": 110,
    "bp_systolic_low": 90,
    # Maternal pulse (bpm)
    "pulse_tachycardia": 100,
    "pulse_tachycardia_severe": 120,
    "pulse_bradycardia": 50,
    # Temperature (°C)
    "temperature_fever": 38.0,
    # Respiratory rate (breaths/min)
    "rr_high": 21,
    "rr_severe": 30,
    # BMI (kg/m²)
    "bmi_low": 18.5,
    "bmi_high": 30.0,
    # Hemoglobin (g/dL) — WHO anemia in pregnancy bands
    "hb_mild": 11.0,       # < 11.0  mild
    "hb_moderate": 10.0,   # < 10.0  moderate
    "hb_severe": 7.0,      # < 7.0   severe
    # Blood glucose (mg/dL; timing/fasting status unknown -> conservative)
    "glucose_elevated": 140,
    "glucose_marked": 200,
    # Platelets (cells/mm³)
    "platelets_low": 100_000,
    "platelets_severe": 50_000,
    # Proteinuria
    "protein_24h_significant": 300,   # mg/24h
    "pcr_significant": 0.3,           # mg/mg
    # Fetal heart rate (bpm)
    "fhr_low": 110,
    "fhr_high": 160,
    # Maternal age (years) — context only
    "age_young": 18,
    "age_advanced": 35,
}

# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class LatestValue:
    """A latest recorded value with (optional) clinical time."""
    value: Any
    event_time: Optional[datetime] = None


@dataclass(frozen=True)
class Flag:
    """One triggered rule."""
    code: str                       # machine code, e.g. "severe_hypertension"
    name: str                       # short human name, e.g. "Severe hypertension"
    severity: str                   # info | warning | severe | critical
    weight: float                   # contribution to referral score
    domain: str                     # maternal | fetal | history
    section: str                    # evidence key
    factor: str
    observed: str                   # display value, e.g. "165 mmHg"
    finding: str                    # advisory sentence (frontend key_findings)
    reason: Optional[str] = None    # advisory referral reason (None for info)
    action: Optional[str] = None    # advisory action (None if not applicable)

    @property
    def key(self) -> Tuple[str, str]:
        return (self.section, self.factor)


@dataclass
class RuleResult:
    risk_level: str
    flags: List[Flag] = field(default_factory=list)
    normal_findings: List[str] = field(default_factory=list)
    actions: List[str] = field(default_factory=list)
    explanation_lines: List[str] = field(default_factory=list)
    referral_recommended: bool = False
    referral_urgency: str = URGENCY_LOW
    referral_score: float = 0.0
    referral_reasons: List[str] = field(default_factory=list)
    data_points_evaluated: int = 0
    engine: str = ENGINE_VERSION
    disclaimer: str = DISCLAIMER

    # Convenience views ----------------------------------------------------
    @property
    def flag_keys(self) -> List[Tuple[str, str]]:
        return [f.key for f in self.flags]

    def flags_at_least(self, severity: str) -> List[Flag]:
        return [f for f in self.flags if _SEV_RANK[f.severity] >= _SEV_RANK[severity]]

    def all_texts(self) -> List[str]:
        """Every human-facing string (used to validate advisory language)."""
        out: List[str] = []
        for f in self.flags:
            out.append(f.finding)
            if f.reason:
                out.append(f.reason)
            if f.action:
                out.append(f.action)
        out.extend(self.normal_findings)
        out.extend(self.actions)
        out.extend(self.explanation_lines)
        out.extend(self.referral_reasons)
        out.append(self.disclaimer)
        return out


# ---------------------------------------------------------------------------
# Value coercion helpers
# ---------------------------------------------------------------------------


def _coerce_latest(raw: Any) -> LatestValue:
    """Accept LatestValue, a stored payload dict ({"value": ..}), or a raw scalar."""
    if isinstance(raw, LatestValue):
        return raw
    if isinstance(raw, dict) and "value" in raw:
        et = raw.get("event_time")
        return LatestValue(value=raw.get("value"), event_time=et if isinstance(et, datetime) else None)
    return LatestValue(value=raw, event_time=None)


def _num(v: Any) -> Optional[float]:
    if v is None or isinstance(v, bool):
        return None
    if isinstance(v, (int, float)):
        f = float(v)
        return f if math.isfinite(f) else None
    if isinstance(v, dict) and "value" in v:
        return _num(v.get("value"))
    if isinstance(v, str):
        s = v.strip().replace(",", "")
        if not s:
            return None
        try:
            f = float(s)
        except ValueError:
            return None
        return f if math.isfinite(f) else None
    return None


def _bool(v: Any) -> Optional[bool]:
    if v is None:
        return None
    if isinstance(v, bool):
        return v
    if isinstance(v, (int, float)):
        if v == 1:
            return True
        if v == 0:
            return False
        return None
    if isinstance(v, dict) and "value" in v:
        return _bool(v.get("value"))
    if isinstance(v, str):
        s = v.strip().lower()
        if s in {"true", "yes", "y", "1", "present"}:
            return True
        if s in {"false", "no", "n", "0", "absent"}:
            return False
    return None


def _text(v: Any) -> Optional[str]:
    if v is None:
        return None
    if isinstance(v, dict) and "value" in v:
        return _text(v.get("value"))
    if isinstance(v, str):
        s = v.strip()
        return s or None
    return str(v)


def _fmt(n: float) -> str:
    return str(int(n)) if float(n).is_integer() else f"{n:g}"


def _sort_time(dt: Optional[datetime]) -> datetime:
    """Sortable time; None sorts oldest, naive treated as UTC."""
    if dt is None:
        return datetime.min.replace(tzinfo=timezone.utc)
    if dt.tzinfo is None:
        return dt.replace(tzinfo=timezone.utc)
    return dt


def _dipstick_grade(v: Any) -> Optional[float]:
    """
    Map dipstick protein enum to a numeric grade:
      Negative -> 0, Trace -> 0.5, + -> 1, ++ -> 2, +++ -> 3, ++++ -> 4
    Returns None when unrecognised.
    """
    s = _text(v)
    if s is None:
        return None
    s = s.strip().lower()
    table = {
        "negative": 0.0, "neg": 0.0, "nil": 0.0, "none": 0.0, "-": 0.0, "0": 0.0,
        "trace": 0.5,
        "+": 1.0, "1+": 1.0, "positive": 1.0,
        "++": 2.0, "2+": 2.0,
        "+++": 3.0, "3+": 3.0,
        "++++": 4.0, "4+": 4.0,
    }
    return table.get(s)


# ---------------------------------------------------------------------------
# Core evaluation
# ---------------------------------------------------------------------------


class _Ctx:
    """Mutable evaluation context (internal)."""

    def __init__(self, latest: Mapping[Tuple[str, str], Any]):
        self.latest: Dict[Tuple[str, str], LatestValue] = {
            tuple(k): _coerce_latest(v) for k, v in latest.items()  # type: ignore[misc]
        }
        self.flags: List[Flag] = []
        self.normal: List[str] = []
        self.evaluated = 0

    def get(self, key: Tuple[str, str]) -> Optional[LatestValue]:
        return self.latest.get(key)

    def get_group(self, keys: Sequence[Tuple[str, str]]) -> Optional[Tuple[Tuple[str, str], LatestValue]]:
        """Most recent LatestValue among several keys (by event_time; ties -> later key in list)."""
        best: Optional[Tuple[Tuple[str, str], LatestValue]] = None
        for k in keys:
            lv = self.latest.get(k)
            if lv is None:
                continue
            if best is None or _sort_time(lv.event_time) >= _sort_time(best[1].event_time):
                best = (k, lv)
        return best

    def add(self, flag: Flag) -> None:
        self.flags.append(flag)

    def has(self, *codes: str) -> bool:
        present = {f.code for f in self.flags}
        return any(c in present for c in codes)


def _eval_blood_pressure(ctx: _Ctx) -> None:
    sys_lv, dia_lv = ctx.get(K_BP_SYS), ctx.get(K_BP_DIA)
    sbp = _num(sys_lv.value) if sys_lv else None
    dbp = _num(dia_lv.value) if dia_lv else None
    if sbp is None and dbp is None:
        return
    ctx.evaluated += int(sbp is not None) + int(dbp is not None)
    T = THRESHOLDS
    bp_txt = f"{_fmt(sbp) if sbp is not None else '?'}/{_fmt(dbp) if dbp is not None else '?'} mmHg"

    severe = (sbp is not None and sbp >= T["bp_systolic_severe"]) or (dbp is not None and dbp >= T["bp_diastolic_severe"])
    elevated = (sbp is not None and sbp >= T["bp_systolic_elevated"]) or (dbp is not None and dbp >= T["bp_diastolic_elevated"])
    low = sbp is not None and sbp < T["bp_systolic_low"]

    # Evidence key: the component that crossed the threshold (systolic preferred).
    def _bp_key(sys_thr: float, dia_thr: float) -> Tuple[str, str]:
        if sbp is not None and sbp >= sys_thr:
            return K_BP_SYS
        if dbp is not None and dbp >= dia_thr:
            return K_BP_DIA
        return K_BP_SYS

    key = _bp_key(T["bp_systolic_severe"], T["bp_diastolic_severe"]) if severe else _bp_key(
        T["bp_systolic_elevated"], T["bp_diastolic_elevated"]
    )

    if severe:
        ctx.add(Flag(
            code="severe_hypertension", name="Severe hypertension", severity=SEV_SEVERE, weight=0.35,
            domain=DOMAIN_MATERNAL, section=key[0], factor=key[1], observed=bp_txt,
            finding=f"Blood pressure: {bp_txt} (⚠️ Severely Elevated, ≥160/110)",
            reason=f"Blood pressure {bp_txt} is in the severe range (≥160 systolic or ≥110 diastolic) and warrants urgent clinician review.",
            action="Severe-range blood pressure warrants urgent clinician review; consider evaluation for severe pre-eclampsia features per local protocol.",
        ))
    elif elevated:
        ctx.add(Flag(
            code="hypertension", name="Elevated blood pressure", severity=SEV_WARNING, weight=0.20,
            domain=DOMAIN_MATERNAL, section=key[0], factor=key[1], observed=bp_txt,
            finding=f"Blood pressure: {bp_txt} (⚠️ Elevated, ≥140/90)",
            reason=f"Blood pressure {bp_txt} is at or above 140/90 mmHg, which may indicate a hypertensive disorder of pregnancy.",
            action="Consider repeating the blood pressure measurement and evaluating for hypertensive disorders of pregnancy.",
        ))
    elif low:
        ctx.add(Flag(
            code="hypotension", name="Low systolic blood pressure", severity=SEV_WARNING, weight=0.15,
            domain=DOMAIN_MATERNAL, section=K_BP_SYS[0], factor=K_BP_SYS[1], observed=bp_txt,
            finding=f"Blood pressure: {bp_txt} (⚠️ Low systolic, <90)",
            reason=f"Systolic blood pressure {_fmt(sbp)} mmHg is below 90 mmHg and warrants clinician review, particularly if bleeding or tachycardia is present.",
            action="Consider evaluating low blood pressure together with pulse, bleeding and hydration status.",
        ))
    else:
        ctx.normal.append(f"Blood pressure: {bp_txt} (Normal range)")


def _eval_pulse(ctx: _Ctx) -> None:
    lv = ctx.get(K_PULSE)  # maternal pulse ONLY -- fetal HR is handled separately
    hr = _num(lv.value) if lv else None
    if hr is None:
        return
    ctx.evaluated += 1
    T = THRESHOLDS
    obs = f"{_fmt(hr)} bpm"
    if hr >= T["pulse_tachycardia_severe"]:
        ctx.add(Flag(
            code="maternal_tachycardia_severe", name="Marked maternal tachycardia", severity=SEV_SEVERE, weight=0.20,
            domain=DOMAIN_MATERNAL, section=K_PULSE[0], factor=K_PULSE[1], observed=obs,
            finding=f"Maternal pulse rate: {obs} (⚠️ Markedly Elevated, ≥120)",
            reason=f"Maternal pulse {obs} is 120 bpm or above and warrants urgent clinician review.",
            action="Consider evaluating marked maternal tachycardia for infection, anemia, bleeding or other causes.",
        ))
    elif hr >= T["pulse_tachycardia"]:
        ctx.add(Flag(
            code="maternal_tachycardia", name="Maternal tachycardia", severity=SEV_WARNING, weight=0.10,
            domain=DOMAIN_MATERNAL, section=K_PULSE[0], factor=K_PULSE[1], observed=obs,
            finding=f"Maternal pulse rate: {obs} (⚠️ Elevated, ≥100)",
            reason=f"Maternal pulse {obs} is 100 bpm or above.",
            action="Consider evaluating maternal tachycardia (infection, anemia, bleeding or other causes).",
        ))
    elif hr < T["pulse_bradycardia"]:
        ctx.add(Flag(
            code="maternal_bradycardia", name="Maternal bradycardia", severity=SEV_WARNING, weight=0.10,
            domain=DOMAIN_MATERNAL, section=K_PULSE[0], factor=K_PULSE[1], observed=obs,
            finding=f"Maternal pulse rate: {obs} (⚠️ Low, <50)",
            reason=f"Maternal pulse {obs} is below 50 bpm.",
            action="Consider clinician review of maternal bradycardia.",
        ))
    else:
        ctx.normal.append(f"Maternal pulse rate: {obs} (Normal range)")


def _eval_temperature(ctx: _Ctx) -> None:
    lv = ctx.get(K_TEMP)
    t = _num(lv.value) if lv else None
    if t is None:
        return
    ctx.evaluated += 1
    obs = f"{_fmt(t)} °C"
    if t >= THRESHOLDS["temperature_fever"]:
        ctx.add(Flag(
            code="fever", name="Fever", severity=SEV_WARNING, weight=0.15,
            domain=DOMAIN_MATERNAL, section=K_TEMP[0], factor=K_TEMP[1], observed=obs,
            finding=f"Temperature: {obs} (⚠️ Elevated, ≥38.0)",
            reason=f"Temperature {obs} is 38.0 °C or above; fever in pregnancy warrants clinician review.",
            action="Consider evaluating for infection; fever in pregnancy warrants clinician review.",
        ))
    else:
        ctx.normal.append(f"Temperature: {obs} (Normal range)")


def _eval_respiratory_rate(ctx: _Ctx) -> None:
    lv = ctx.get(K_RR)
    rr = _num(lv.value) if lv else None
    if rr is None:
        return
    ctx.evaluated += 1
    obs = f"{_fmt(rr)} breaths/min"
    if rr >= THRESHOLDS["rr_severe"]:
        ctx.add(Flag(
            code="tachypnoea_severe", name="Marked tachypnoea", severity=SEV_SEVERE, weight=0.20,
            domain=DOMAIN_MATERNAL, section=K_RR[0], factor=K_RR[1], observed=obs,
            finding=f"Respiratory rate: {obs} (⚠️ Markedly Elevated, ≥30)",
            reason=f"Respiratory rate {obs} is 30 or above and warrants urgent clinician review.",
            action="Marked tachypnoea warrants urgent clinician review.",
        ))
    elif rr >= THRESHOLDS["rr_high"]:
        ctx.add(Flag(
            code="tachypnoea", name="Raised respiratory rate", severity=SEV_WARNING, weight=0.10,
            domain=DOMAIN_MATERNAL, section=K_RR[0], factor=K_RR[1], observed=obs,
            finding=f"Respiratory rate: {obs} (⚠️ Elevated, ≥21)",
            reason=f"Respiratory rate {obs} is above the usual range.",
            action="Consider clinician review of raised respiratory rate.",
        ))
    else:
        ctx.normal.append(f"Respiratory rate: {obs} (Normal range)")


def _eval_bmi(ctx: _Ctx) -> None:
    lv = ctx.get(K_BMI)
    bmi = _num(lv.value) if lv else None
    if bmi is None:
        return
    ctx.evaluated += 1
    obs = f"{_fmt(round(bmi, 1))} kg/m²"
    if bmi >= THRESHOLDS["bmi_high"]:
        ctx.add(Flag(
            code="bmi_high", name="High BMI", severity=SEV_INFO, weight=0.05,
            domain=DOMAIN_MATERNAL, section=K_BMI[0], factor=K_BMI[1], observed=obs,
            finding=f"Body mass index: {obs} (High, ≥30)",
        ))
    elif bmi < THRESHOLDS["bmi_low"]:
        ctx.add(Flag(
            code="bmi_low", name="Low BMI", severity=SEV_INFO, weight=0.05,
            domain=DOMAIN_MATERNAL, section=K_BMI[0], factor=K_BMI[1], observed=obs,
            finding=f"Body mass index: {obs} (Low, <18.5)",
        ))
    else:
        ctx.normal.append(f"Body mass index: {obs} (Normal range)")


def _eval_hemoglobin(ctx: _Ctx) -> None:
    lv = ctx.get(K_HB)
    hb = _num(lv.value) if lv else None
    if hb is None:
        return
    ctx.evaluated += 1
    T = THRESHOLDS
    obs = f"{_fmt(hb)} g/dL"
    if hb < T["hb_severe"]:
        ctx.add(Flag(
            code="severe_anemia", name="Severe anemia", severity=SEV_SEVERE, weight=0.30,
            domain=DOMAIN_MATERNAL, section=K_HB[0], factor=K_HB[1], observed=obs,
            finding=f"Hemoglobin: {obs} (⚠️ Low, severe anemia range <7)",
            reason=f"Hemoglobin {obs} is below 7 g/dL (severe anemia range) and warrants urgent clinician review.",
            action="Severe anemia warrants urgent clinician review; consider referral for further evaluation and management per local protocol.",
        ))
    elif hb < T["hb_moderate"]:
        ctx.add(Flag(
            code="moderate_anemia", name="Moderate anemia", severity=SEV_WARNING, weight=0.15,
            domain=DOMAIN_MATERNAL, section=K_HB[0], factor=K_HB[1], observed=obs,
            finding=f"Hemoglobin: {obs} (⚠️ Low, moderate anemia range 7–9.9)",
            reason=f"Hemoglobin {obs} is in the moderate anemia range (7–9.9 g/dL).",
            action="Consider anemia work-up and iron/folate supplementation per antenatal care guidance.",
        ))
    elif hb < T["hb_mild"]:
        ctx.add(Flag(
            code="mild_anemia", name="Mild anemia", severity=SEV_INFO, weight=0.05,
            domain=DOMAIN_MATERNAL, section=K_HB[0], factor=K_HB[1], observed=obs,
            finding=f"Hemoglobin: {obs} (Low, mild anemia range 10–10.9)",
            action="Consider iron/folate supplementation and repeat hemoglobin per antenatal care guidance.",
        ))
    else:
        ctx.normal.append(f"Hemoglobin: {obs} (Normal range)")


def _eval_glucose(ctx: _Ctx) -> None:
    lv = ctx.get(K_GLUCOSE)
    g = _num(lv.value) if lv else None
    if g is None:
        return
    ctx.evaluated += 1
    obs = f"{_fmt(g)} mg/dL"
    if g >= THRESHOLDS["glucose_marked"]:
        ctx.add(Flag(
            code="hyperglycaemia_marked", name="Markedly elevated blood glucose", severity=SEV_WARNING, weight=0.20,
            domain=DOMAIN_MATERNAL, section=K_GLUCOSE[0], factor=K_GLUCOSE[1], observed=obs,
            finding=f"Blood glucose: {obs} (⚠️ Markedly Elevated, ≥200)",
            reason=f"Blood glucose {obs} is 200 mg/dL or above and warrants clinician review.",
            action="Consider formal glucose testing to evaluate for gestational or pre-existing diabetes.",
        ))
    elif g >= THRESHOLDS["glucose_elevated"]:
        ctx.add(Flag(
            code="hyperglycaemia", name="Elevated blood glucose", severity=SEV_WARNING, weight=0.10,
            domain=DOMAIN_MATERNAL, section=K_GLUCOSE[0], factor=K_GLUCOSE[1], observed=obs,
            finding=f"Blood glucose: {obs} (⚠️ Elevated, ≥140)",
            reason=f"Blood glucose {obs} is 140 mg/dL or above.",
            action="Consider formal glucose testing to evaluate for gestational diabetes.",
        ))
    else:
        ctx.normal.append(f"Blood glucose: {obs} (Normal range)")


def _eval_platelets(ctx: _Ctx) -> None:
    lv = ctx.get(K_PLATELETS)
    p = _num(lv.value) if lv else None
    if p is None:
        return
    ctx.evaluated += 1
    obs = f"{_fmt(p)} /mm³"
    if p < THRESHOLDS["platelets_severe"]:
        ctx.add(Flag(
            code="thrombocytopenia_severe", name="Severe thrombocytopenia", severity=SEV_SEVERE, weight=0.25,
            domain=DOMAIN_MATERNAL, section=K_PLATELETS[0], factor=K_PLATELETS[1], observed=obs,
            finding=f"Platelet count: {obs} (⚠️ Low, <50,000)",
            reason=f"Platelet count {obs} is below 50,000/mm³ and warrants urgent clinician review.",
            action="Low platelet count warrants urgent clinician review, particularly alongside blood pressure findings.",
        ))
    elif p < THRESHOLDS["platelets_low"]:
        ctx.add(Flag(
            code="thrombocytopenia", name="Low platelet count", severity=SEV_WARNING, weight=0.15,
            domain=DOMAIN_MATERNAL, section=K_PLATELETS[0], factor=K_PLATELETS[1], observed=obs,
            finding=f"Platelet count: {obs} (⚠️ Low, <100,000)",
            reason=f"Platelet count {obs} is below 100,000/mm³.",
            action="Low platelet count warrants clinician review, particularly alongside blood pressure findings.",
        ))
    else:
        ctx.normal.append(f"Platelet count: {obs} (Normal range)")


def _eval_proteinuria(ctx: _Ctx) -> None:
    # Dipstick
    lv = ctx.get(K_DIPSTICK)
    grade = _dipstick_grade(lv.value) if lv else None
    if lv is not None and grade is not None:
        ctx.evaluated += 1
        raw = _text(lv.value) or ""
        if grade >= 2:
            ctx.add(Flag(
                code="proteinuria_significant", name="Significant proteinuria", severity=SEV_WARNING, weight=0.20,
                domain=DOMAIN_MATERNAL, section=K_DIPSTICK[0], factor=K_DIPSTICK[1], observed=raw,
                finding=f"Urine dipstick protein: {raw} (⚠️ Elevated, ++ or more)",
                reason=f"Urine dipstick protein '{raw}' indicates significant proteinuria and may be relevant to pre-eclampsia risk when combined with blood pressure.",
                action="Consider correlating proteinuria with blood pressure and symptoms to evaluate pre-eclampsia risk.",
            ))
        elif grade >= 1:
            ctx.add(Flag(
                code="proteinuria", name="Proteinuria", severity=SEV_WARNING, weight=0.15,
                domain=DOMAIN_MATERNAL, section=K_DIPSTICK[0], factor=K_DIPSTICK[1], observed=raw,
                finding=f"Urine dipstick protein: {raw} (⚠️ Elevated, 1+)",
                reason=f"Urine dipstick protein '{raw}' may indicate proteinuria.",
                action="Consider correlating proteinuria with blood pressure and symptoms to evaluate pre-eclampsia risk.",
            ))
        elif grade > 0:
            ctx.add(Flag(
                code="proteinuria_trace", name="Trace proteinuria", severity=SEV_INFO, weight=0.0,
                domain=DOMAIN_MATERNAL, section=K_DIPSTICK[0], factor=K_DIPSTICK[1], observed=raw,
                finding=f"Urine dipstick protein: {raw} (Trace)",
            ))
        else:
            ctx.normal.append(f"Urine dipstick protein: {raw} (Normal)")

    # Quantitative measures
    lv24 = ctx.get(K_PROTEIN_24H)
    p24 = _num(lv24.value) if lv24 else None
    if p24 is not None:
        ctx.evaluated += 1
        obs = f"{_fmt(p24)} mg/24h"
        if p24 >= THRESHOLDS["protein_24h_significant"]:
            ctx.add(Flag(
                code="proteinuria_24h", name="Proteinuria (24-hour urine)", severity=SEV_WARNING, weight=0.15,
                domain=DOMAIN_MATERNAL, section=K_PROTEIN_24H[0], factor=K_PROTEIN_24H[1], observed=obs,
                finding=f"24-hour urine protein: {obs} (⚠️ Elevated, ≥300)",
                reason=f"24-hour urine protein {obs} is 300 mg or above, which may indicate significant proteinuria.",
                action="Consider correlating proteinuria with blood pressure and symptoms to evaluate pre-eclampsia risk.",
            ))
        else:
            ctx.normal.append(f"24-hour urine protein: {obs} (Normal range)")

    lvpcr = ctx.get(K_PCR)
    pcr = _num(lvpcr.value) if lvpcr else None
    if pcr is not None:
        ctx.evaluated += 1
        obs = f"{_fmt(pcr)} mg/mg"
        if pcr >= THRESHOLDS["pcr_significant"]:
            ctx.add(Flag(
                code="proteinuria_pcr", name="Proteinuria (protein:creatinine ratio)", severity=SEV_WARNING, weight=0.15,
                domain=DOMAIN_MATERNAL, section=K_PCR[0], factor=K_PCR[1], observed=obs,
                finding=f"Urine protein:creatinine ratio: {obs} (⚠️ Elevated, ≥0.3)",
                reason=f"Protein:creatinine ratio {obs} is 0.3 or above, which may indicate significant proteinuria.",
                action="Consider correlating proteinuria with blood pressure and symptoms to evaluate pre-eclampsia risk.",
            ))
        else:
            ctx.normal.append(f"Urine protein:creatinine ratio: {obs} (Normal range)")


def _eval_symptoms(ctx: _Ctx) -> None:
    # Headache / epigastric pain / visual symptoms (2nd/3rd trimester ANC)
    got = ctx.get_group(GROUP_SYMPTOMS)
    if got:
        key, lv = got
        b = _bool(lv.value)
        if b is not None:
            ctx.evaluated += 1
            if b:
                ctx.add(Flag(
                    code="preeclampsia_symptoms", name="Headache / epigastric pain / visual symptoms",
                    severity=SEV_WARNING, weight=0.15, domain=DOMAIN_MATERNAL, section=key[0], factor=key[1],
                    observed="reported",
                    finding="Headache, epigastric pain or visual symptoms: reported (⚠️ Warning sign)",
                    reason="Headache, epigastric pain or visual disturbance was reported; these symptoms may be relevant to pre-eclampsia risk, particularly with raised blood pressure.",
                    action="Reported headache, epigastric pain or visual symptoms warrant clinician review, particularly alongside blood pressure findings.",
                ))
            else:
                ctx.normal.append("Headache, epigastric pain or visual symptoms: not reported (Normal)")

    # Vaginal bleeding / discharge (1st/3rd trimester ANC)
    got = ctx.get_group(GROUP_BLEEDING)
    if got:
        key, lv = got
        b = _bool(lv.value)
        if b is not None:
            ctx.evaluated += 1
            if b:
                ctx.add(Flag(
                    code="vaginal_bleeding", name="Vaginal bleeding or discharge",
                    severity=SEV_WARNING, weight=0.20, domain=DOMAIN_MATERNAL, section=key[0], factor=key[1],
                    observed="reported",
                    finding="Vaginal bleeding or discharge: reported (⚠️ Warning sign)",
                    reason="Vaginal bleeding or abnormal discharge was reported and warrants prompt clinician assessment.",
                    action="Reported vaginal bleeding or discharge warrants prompt clinician assessment.",
                ))
            else:
                ctx.normal.append("Vaginal bleeding or discharge: not reported (Normal)")

    # Fever or urinary symptoms (any trimester ANC)
    got = ctx.get_group(GROUP_FEVER_URINARY)
    if got:
        key, lv = got
        b = _bool(lv.value)
        if b is not None:
            ctx.evaluated += 1
            if b:
                ctx.add(Flag(
                    code="fever_or_urinary_symptoms", name="Fever or urinary symptoms",
                    severity=SEV_WARNING, weight=0.10, domain=DOMAIN_MATERNAL, section=key[0], factor=key[1],
                    observed="reported",
                    finding="Fever or urinary symptoms: reported (⚠️ Warning sign)",
                    reason="Fever or urinary symptoms were reported and may indicate infection.",
                    action="Consider evaluating reported fever or urinary symptoms for infection.",
                ))
            else:
                ctx.normal.append("Fever or urinary symptoms: not reported (Normal)")

    # Reduced fetal movement (3rd trimester ANC: fetal_movement_normal == False)
    lv = ctx.get(K_FETAL_MOVEMENT_T3)
    if lv is not None:
        b = _bool(lv.value)
        if b is not None:
            ctx.evaluated += 1
            if b is False:
                ctx.add(Flag(
                    code="reduced_fetal_movement", name="Reduced fetal movement",
                    severity=SEV_WARNING, weight=0.15, domain=DOMAIN_FETAL,
                    section=K_FETAL_MOVEMENT_T3[0], factor=K_FETAL_MOVEMENT_T3[1], observed="not normal",
                    finding="Fetal movement: reported as not normal (⚠️ Warning sign)",
                    reason="Fetal movement was reported as not normal and warrants prompt assessment of fetal well-being.",
                    action="Reported reduced fetal movement warrants prompt clinician assessment of fetal well-being.",
                ))
            else:
                ctx.normal.append("Fetal movement: reported as normal (Normal)")


def _eval_general(ctx: _Ctx) -> None:
    lv = ctx.get(K_CONSCIOUSNESS)
    loc = _text(lv.value) if lv else None
    if loc:
        ctx.evaluated += 1
        lvl = loc.lower()
        if lvl == "unconscious":
            ctx.add(Flag(
                code="unconscious", name="Unconscious", severity=SEV_CRITICAL, weight=0.50,
                domain=DOMAIN_MATERNAL, section=K_CONSCIOUSNESS[0], factor=K_CONSCIOUSNESS[1], observed=loc,
                finding=f"Level of consciousness: {loc} (⚠️ Critical sign)",
                reason="Recorded level of consciousness is 'Unconscious', which warrants emergency clinician review.",
                action="An unconscious patient warrants emergency clinician review and consideration of immediate referral per local protocol.",
            ))
        elif lvl in {"drowsy", "confused"}:
            ctx.add(Flag(
                code="altered_consciousness", name="Altered consciousness", severity=SEV_SEVERE, weight=0.30,
                domain=DOMAIN_MATERNAL, section=K_CONSCIOUSNESS[0], factor=K_CONSCIOUSNESS[1], observed=loc,
                finding=f"Level of consciousness: {loc} (⚠️ Abnormal)",
                reason=f"Recorded level of consciousness is '{loc}', which warrants urgent clinician review.",
                action="Altered level of consciousness warrants urgent clinician review.",
            ))
        else:
            ctx.normal.append(f"Level of consciousness: {loc} (Normal)")

    for key, code, name, text_ in (
        (K_PALLOR, "pallor", "Pallor", "Pallor: present (may accompany anemia)"),
        (K_EDEMA, "edema", "Edema", "Edema: present (may be relevant alongside blood pressure findings)"),
    ):
        lv = ctx.get(key)
        if lv is None:
            continue
        b = _bool(lv.value)
        if b is None:
            continue
        ctx.evaluated += 1
        if b:
            ctx.add(Flag(
                code=code, name=name, severity=SEV_INFO, weight=0.05,
                domain=DOMAIN_MATERNAL, section=key[0], factor=key[1], observed="present",
                finding=text_,
            ))
        else:
            ctx.normal.append(f"{name}: absent (Normal)")


def _eval_fetal_heart_rate(ctx: _Ctx) -> None:
    got = ctx.get_group(GROUP_FHR)
    if not got:
        return
    key, lv = got
    fhr = _num(lv.value)
    if fhr is None:
        return
    ctx.evaluated += 1
    obs = f"{_fmt(fhr)} bpm"
    src = "ultrasound" if key == K_FHR_USG else "abdominal examination"
    if fhr < THRESHOLDS["fhr_low"]:
        ctx.add(Flag(
            code="fetal_bradycardia", name="Fetal bradycardia", severity=SEV_WARNING, weight=0.20,
            domain=DOMAIN_FETAL, section=key[0], factor=key[1], observed=obs,
            finding=f"Fetal heart rate ({src}): {obs} (⚠️ Low, <110)",
            reason=f"Fetal heart rate {obs} is below 110 bpm and warrants clinician review and repeat assessment.",
            action="Fetal heart rate outside the usual 110–160 bpm range warrants clinician review and repeat assessment.",
        ))
    elif fhr > THRESHOLDS["fhr_high"]:
        ctx.add(Flag(
            code="fetal_tachycardia", name="Fetal tachycardia", severity=SEV_WARNING, weight=0.15,
            domain=DOMAIN_FETAL, section=key[0], factor=key[1], observed=obs,
            finding=f"Fetal heart rate ({src}): {obs} (⚠️ Elevated, >160)",
            reason=f"Fetal heart rate {obs} is above 160 bpm and warrants clinician review and repeat assessment.",
            action="Fetal heart rate outside the usual 110–160 bpm range warrants clinician review and repeat assessment.",
        ))
    else:
        ctx.normal.append(f"Fetal heart rate ({src}): {obs} (Normal range 110–160)")


def _eval_history(ctx: _Ctx, patient_age: Optional[int]) -> None:
    lv = ctx.get(K_PLACENTA)
    loc = _text(lv.value) if lv else None
    if loc:
        ctx.evaluated += 1
        if loc.strip().lower() in {"low-lying", "low lying", "previa", "placenta previa"}:
            ctx.add(Flag(
                code="placenta_previa_or_low_lying", name="Low-lying placenta / placenta previa",
                severity=SEV_WARNING, weight=0.10, domain=DOMAIN_MATERNAL,
                section=K_PLACENTA[0], factor=K_PLACENTA[1], observed=loc,
                finding=f"Placental location on ultrasound: {loc} (⚠️ Abnormal)",
                reason=f"Ultrasound placental location '{loc}' warrants clinician review and planning of delivery at an appropriate facility.",
                action="Low-lying placenta or placenta previa on ultrasound warrants clinician review and delivery planning at an appropriate facility.",
            ))
        else:
            ctx.normal.append(f"Placental location on ultrasound: {loc} (Normal)")

    for key, code, name, text_ in (
        (K_HX_HTN, "history_hypertension", "History of hypertension", "Past medical history: hypertension (History)"),
        (K_HX_DM, "history_diabetes", "History of diabetes", "Past medical history: diabetes (History)"),
    ):
        lv = ctx.get(key)
        if lv is None:
            continue
        b = _bool(lv.value)
        if b is None:
            continue
        ctx.evaluated += 1
        if b:
            ctx.add(Flag(
                code=code, name=name, severity=SEV_INFO, weight=0.05,
                domain=DOMAIN_HISTORY, section=key[0], factor=key[1], observed="yes",
                finding=text_,
            ))

    lv = ctx.get(K_HX_LOSS)
    loss = _text(lv.value) if lv else None
    if loss:
        ctx.evaluated += 1
        if loss.strip().lower() not in {"none", "no", "false"}:
            ctx.add(Flag(
                code="history_pregnancy_loss", name="Previous pregnancy loss", severity=SEV_INFO, weight=0.05,
                domain=DOMAIN_HISTORY, section=K_HX_LOSS[0], factor=K_HX_LOSS[1], observed=loss,
                finding=f"Obstetric history: previous {loss.lower()} (History)",
            ))

    lv = ctx.get(K_HX_COMPLICATIONS)
    comp = _text(lv.value) if lv else None
    if comp and comp.strip().lower() not in {"none", "no", "nil", "n/a", "na", "false"}:
        ctx.evaluated += 1
        ctx.add(Flag(
            code="history_previous_complications", name="Previous pregnancy complications", severity=SEV_INFO, weight=0.05,
            domain=DOMAIN_HISTORY, section=K_HX_COMPLICATIONS[0], factor=K_HX_COMPLICATIONS[1], observed=comp[:80],
            finding=f"Obstetric history: previous complications recorded ({comp[:80]}) (History)",
        ))

    if patient_age is not None:
        try:
            age = int(patient_age)
        except (TypeError, ValueError):
            age = None
        if age is not None:
            if age >= THRESHOLDS["age_advanced"]:
                ctx.add(Flag(
                    code="age_advanced", name="Maternal age 35 or above", severity=SEV_INFO, weight=0.05,
                    domain=DOMAIN_HISTORY, section="patient", factor="age_in_years", observed=f"{age} years",
                    finding=f"Maternal age: {age} years (History, ≥35)",
                ))
            elif age < THRESHOLDS["age_young"]:
                ctx.add(Flag(
                    code="age_young", name="Maternal age under 18", severity=SEV_INFO, weight=0.05,
                    domain=DOMAIN_HISTORY, section="patient", factor="age_in_years", observed=f"{age} years",
                    finding=f"Maternal age: {age} years (History, <18)",
                ))


# ---------------------------------------------------------------------------
# Combination rules and risk level
# ---------------------------------------------------------------------------


def _combination_rules(ctx: _Ctx) -> Tuple[List[str], str]:
    """
    Returns (extra_reason_lines, floor_level) where floor_level is the minimum
    overall risk level implied by combinations of flags.
    """
    reasons: List[str] = []
    floor = RISK_LOW

    def raise_to(level: str) -> None:
        nonlocal floor
        if RISK_LEVELS.index(level) > RISK_LEVELS.index(floor):
            floor = level

    proteinuria = ctx.has("proteinuria", "proteinuria_significant", "proteinuria_24h", "proteinuria_pcr")
    symptoms = ctx.has("preeclampsia_symptoms")
    severe_bp = ctx.has("severe_hypertension")
    elevated_bp = ctx.has("hypertension")
    tachy = ctx.has("maternal_tachycardia", "maternal_tachycardia_severe")

    if severe_bp and (proteinuria or symptoms):
        raise_to(RISK_CRITICAL)
        reasons.append(
            "Severe-range blood pressure together with proteinuria and/or headache, epigastric pain or visual symptoms "
            "may indicate severe pre-eclampsia features; urgent clinician review and consideration of immediate referral is advised."
        )
    elif elevated_bp and (proteinuria or symptoms):
        raise_to(RISK_HIGH)
        reasons.append(
            "Raised blood pressure together with proteinuria and/or symptoms may indicate pre-eclampsia; "
            "early clinician review and consideration of referral is advised."
        )

    if ctx.has("vaginal_bleeding") and (tachy or ctx.has("hypotension")):
        raise_to(RISK_HIGH)
        reasons.append(
            "Reported vaginal bleeding together with tachycardia or low blood pressure may indicate significant blood loss; "
            "urgent clinician review is advised."
        )

    if ctx.has("fever") and tachy:
        raise_to(RISK_HIGH)
        reasons.append(
            "Fever together with maternal tachycardia may indicate infection; urgent clinician review is advised."
        )

    if ctx.has("severe_hypertension") and ctx.has("thrombocytopenia", "thrombocytopenia_severe"):
        raise_to(RISK_CRITICAL)
        reasons.append(
            "Severe-range blood pressure together with a low platelet count may indicate severe pre-eclampsia/HELLP features; "
            "urgent clinician review is advised."
        )

    # Several concurrent warning-level maternal findings
    maternal_warnings = [
        f for f in ctx.flags
        if f.domain == DOMAIN_MATERNAL and _SEV_RANK[f.severity] >= _SEV_RANK[SEV_WARNING]
    ]
    if len(maternal_warnings) >= 3:
        raise_to(RISK_HIGH)
        reasons.append(
            f"{len(maternal_warnings)} concurrent maternal findings are outside the rule thresholds; "
            "early clinician review and consideration of referral is advised."
        )

    return reasons, floor


def _level_from_flags(flags: Iterable[Flag]) -> str:
    worst = SEV_INFO
    any_flag = False
    for f in flags:
        any_flag = True
        if _SEV_RANK[f.severity] > _SEV_RANK[worst]:
            worst = f.severity
    if not any_flag:
        return RISK_LOW
    return {
        SEV_INFO: RISK_LOW,
        SEV_WARNING: RISK_MEDIUM,
        SEV_SEVERE: RISK_HIGH,
        SEV_CRITICAL: RISK_CRITICAL,
    }[worst]


def _max_level(a: str, b: str) -> str:
    return a if RISK_LEVELS.index(a) >= RISK_LEVELS.index(b) else b


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def evaluate_latest_values(
    latest: Mapping[Tuple[str, str], Any],
    *,
    patient_age: Optional[int] = None,
) -> RuleResult:
    """
    Evaluate the LATEST value per (section, factor) and return a RuleResult.

    `latest` values may be:
      - `LatestValue(value, event_time)`
      - the stored ClinicalEvent payload dict `{"value": ..., "unit": ..., "type": ...}`
      - a raw scalar (number / bool / str)

    Only keys defined in `RULE_INPUT_KEYS` are read; anything else is ignored.
    The function is deterministic and side-effect free.
    """
    ctx = _Ctx(latest)

    _eval_blood_pressure(ctx)
    _eval_pulse(ctx)
    _eval_temperature(ctx)
    _eval_respiratory_rate(ctx)
    _eval_bmi(ctx)
    _eval_hemoglobin(ctx)
    _eval_glucose(ctx)
    _eval_platelets(ctx)
    _eval_proteinuria(ctx)
    _eval_symptoms(ctx)
    _eval_general(ctx)
    _eval_fetal_heart_rate(ctx)
    _eval_history(ctx, patient_age)

    combo_reasons, floor = _combination_rules(ctx)

    if ctx.evaluated == 0:
        level = RISK_UNKNOWN
    else:
        level = _max_level(_level_from_flags(ctx.flags), floor)

    # Order flags: most severe first, then heaviest weight
    flags = sorted(ctx.flags, key=lambda f: (-_SEV_RANK[f.severity], -f.weight, f.code))

    # Actions (de-duplicated, order preserved)
    actions: List[str] = []
    for f in flags:
        if f.action and f.action not in actions:
            actions.append(f.action)

    # Referral logic (from level, not from score)
    referral_recommended = level in (RISK_MEDIUM, RISK_HIGH, RISK_CRITICAL)
    urgency = {
        RISK_CRITICAL: URGENCY_CRITICAL,
        RISK_HIGH: URGENCY_HIGH,
        RISK_MEDIUM: URGENCY_MEDIUM,
    }.get(level, URGENCY_LOW)

    score = min(REFERRAL_SCORE_CAP, round(sum(f.weight for f in flags), 2))

    reasons: List[str] = list(combo_reasons)
    for f in flags:
        if f.reason and _SEV_RANK[f.severity] >= _SEV_RANK[SEV_WARNING] and f.reason not in reasons:
            reasons.append(f.reason)

    explanation: List[str] = []
    if level == RISK_UNKNOWN:
        explanation.append(
            "No clinical measurements that the advisory rules evaluate have been recorded for this patient yet, "
            "so an overall risk level cannot be estimated. Recording vitals, investigations and ANC findings "
            "allows the rules to run."
        )
        reasons = [
            "No clinical measurements are recorded yet; the advisory rules cannot evaluate referral need until data is entered."
        ]
    else:
        explanation.extend(combo_reasons)
        for f in flags:
            explanation.append(f.finding)
        if not flags:
            explanation.append(
                "The latest recorded values did not cross any advisory rule threshold. This does not exclude risk; "
                "the assessment is limited by data completeness and recency."
            )
            reasons = [
                "No findings outside the rule thresholds were detected in the latest recorded values; "
                "routine antenatal follow-up may continue with clinician review as usual."
            ]
        elif not referral_recommended:
            reasons = [
                "Only low-severity or contextual findings were detected in the latest recorded values; "
                "routine antenatal follow-up may continue with clinician review as usual."
            ]

    result = RuleResult(
        risk_level=level,
        flags=flags,
        normal_findings=list(ctx.normal),
        actions=actions,
        explanation_lines=explanation,
        referral_recommended=referral_recommended,
        referral_urgency=urgency,
        referral_score=score,
        referral_reasons=reasons,
        data_points_evaluated=ctx.evaluated,
    )

    # Guardrail: every human-facing string is advisory.
    for text in result.all_texts():
        validate_advisory_language(text)

    return result


def build_summary_text(result: RuleResult, *, age: Optional[Any] = None, event_count: int = 0) -> str:
    """Short clinician-facing summary sentence used by both engines."""
    who = f"Patient ({age} years)" if age not in (None, "", "Unknown") else "Patient"
    warn = result.flags_at_least(SEV_WARNING)
    if result.risk_level == RISK_UNKNOWN:
        return (
            f"{who}: no clinical measurements have been recorded yet, so the advisory rules could not "
            "estimate a risk level. Assessment pending data entry."
        )
    if warn:
        return (
            f"{who}: {len(warn)} finding(s) outside advisory rule thresholds in the latest recorded values "
            f"({event_count} clinical entries reviewed). Overall advisory risk level: {result.risk_level}. "
            "Clinician review is advised."
        )
    if result.flags:
        return (
            f"{who}: only low-severity or contextual findings in the latest recorded values "
            f"({event_count} clinical entries reviewed). Overall advisory risk level: {result.risk_level}."
        )
    return (
        f"{who}: latest recorded values are within advisory rule thresholds "
        f"({event_count} clinical entries reviewed). Overall advisory risk level: {result.risk_level}."
    )


__all__ = [
    "ENGINE_VERSION", "DISCLAIMER", "THRESHOLDS", "RULE_INPUT_KEYS",
    "RISK_LEVELS", "URGENCY_LEVELS",
    "RISK_UNKNOWN", "RISK_LOW", "RISK_MEDIUM", "RISK_HIGH", "RISK_CRITICAL",
    "URGENCY_LOW", "URGENCY_MEDIUM", "URGENCY_HIGH", "URGENCY_CRITICAL",
    "SEV_INFO", "SEV_WARNING", "SEV_SEVERE", "SEV_CRITICAL",
    "LatestValue", "Flag", "RuleResult",
    "evaluate_latest_values", "build_summary_text",
]
