"""0001_baseline: the full Phase-1 schema (pre-Alembic state).

Revision ID: 0001_baseline
Revises: (none)
Create Date: 2026-08-18

This is the schema that `Base.metadata.create_all()` + the old init_db ensure-column helpers produced
before Alembic was introduced (9 tables, incl. the two legacy facility tables and the enum types
`user_role` / `referral_status`). Existing PostgreSQL databases that already have these tables are
stamped at this revision by app.db.init_db (see `_stamp_legacy_database`) and then upgraded.

Autogenerated against a fresh PostgreSQL 16 database and hand-checked for portability.

Portability rules (this project runs migrations on PostgreSQL AND SQLite):
- UUID columns: sa.Uuid()
- JSON columns: sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")
- enums: sa.Enum(..., name="...")
- ALTER TABLE: use op.batch_alter_table(...) so SQLite works.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('hospital_facilities',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_facilities_created_at'), 'hospital_facilities', ['created_at'], unique=False)
    op.create_index(op.f('ix_hospital_facilities_id'), 'hospital_facilities', ['id'], unique=False)
    op.create_index(op.f('ix_hospital_facilities_name'), 'hospital_facilities', ['name'], unique=True)
    op.create_table('phc_facilities',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phc_facilities_created_at'), 'phc_facilities', ['created_at'], unique=False)
    op.create_index(op.f('ix_phc_facilities_id'), 'phc_facilities', ['id'], unique=False)
    op.create_index(op.f('ix_phc_facilities_name'), 'phc_facilities', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('nmc_number', sa.String(length=64), nullable=True),
    sa.Column('working_hospital', sa.String(length=255), nullable=True),
    sa.Column('facility_type', sa.String(length=32), nullable=True),
    sa.Column('facility_id', sa.Uuid(), nullable=True),
    sa.Column('facility_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'CLINICIAN', 'HOSPITAL', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_card_image_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_approved'), 'users', ['is_approved'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_action_time', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('patient_id', sa.String(length=20), nullable=False),
    sa.Column('facility_mrn', sa.String(length=64), nullable=True),
    sa.Column('national_id', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('middle_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('age_in_years', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=32), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('address_line', sa.Text(), nullable=True),
    sa.Column('ward', sa.String(length=64), nullable=True),
    sa.Column('municipality', sa.String(length=128), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('province', sa.String(length=128), nullable=True),
    sa.Column('registered_facility_name', sa.String(length=255), nullable=True),
    sa.Column('registered_facility_type', sa.String(length=32), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_age_in_years'), 'patients', ['age_in_years'], unique=False)
    op.create_index(op.f('ix_patients_created_at'), 'patients', ['created_at'], unique=False)
    op.create_index(op.f('ix_patients_created_by_user_id'), 'patients', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_patients_district'), 'patients', ['district'], unique=False)
    op.create_index(op.f('ix_patients_facility_mrn'), 'patients', ['facility_mrn'], unique=False)
    op.create_index('ix_patients_facility_mrn_uniqueish', 'patients', ['facility_mrn'], unique=False)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index('ix_patients_name_age', 'patients', ['last_name', 'first_name', 'age_in_years'], unique=False)
    op.create_index(op.f('ix_patients_national_id'), 'patients', ['national_id'], unique=False)
    op.create_index('ix_patients_national_id_uniqueish', 'patients', ['national_id'], unique=False)
    op.create_index(op.f('ix_patients_patient_id'), 'patients', ['patient_id'], unique=True)
    op.create_index(op.f('ix_patients_phone_number'), 'patients', ['phone_number'], unique=False)
    op.create_index(op.f('ix_patients_registered_facility_name'), 'patients', ['registered_facility_name'], unique=False)
    op.create_table('ai_patient_analyses',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('referral_needed', sa.Boolean(), nullable=True),
    sa.Column('referral_urgency', sa.String(length=20), nullable=True),
    sa.Column('referral_confidence', sa.Float(), nullable=True),
    sa.Column('referral_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('recommended_facility', sa.String(length=255), nullable=True),
    sa.Column('recommended_specialties', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('risk_factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('clinical_indicators', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_patient_analyses_created_at'), 'ai_patient_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_patient_analyses_id'), 'ai_patient_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_ai_patient_analyses_patient_id'), 'ai_patient_analyses', ['patient_id'], unique=True)
    op.create_table('referrals',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('from_facility', sa.String(length=200), nullable=False),
    sa.Column('to_facility', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'RECEIVED', 'CLOSED', 'CANCELLED', name='referral_status'), nullable=False),
    sa.Column('received_facility_status', sa.Enum('DRAFT', 'SUBMITTED', 'RECEIVED', 'CLOSED', 'CANCELLED', name='referral_status'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reason_codes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ai_recommendation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('clinician_decision', sa.String(length=64), nullable=True),
    sa.Column('clinician_note', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_closed_at'), 'referrals', ['closed_at'], unique=False)
    op.create_index(op.f('ix_referrals_created_at'), 'referrals', ['created_at'], unique=False)
    op.create_index(op.f('ix_referrals_created_by_user_id'), 'referrals', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_referrals_from_facility'), 'referrals', ['from_facility'], unique=False)
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.create_index(op.f('ix_referrals_patient_id'), 'referrals', ['patient_id'], unique=False)
    op.create_index('ix_referrals_patient_status', 'referrals', ['patient_id', 'status'], unique=False)
    op.create_index(op.f('ix_referrals_received_at'), 'referrals', ['received_at'], unique=False)
    op.create_index(op.f('ix_referrals_received_facility_status'), 'referrals', ['received_facility_status'], unique=False)
    op.create_index('ix_referrals_route', 'referrals', ['from_facility', 'to_facility'], unique=False)
    op.create_index(op.f('ix_referrals_status'), 'referrals', ['status'], unique=False)
    op.create_index(op.f('ix_referrals_submitted_at'), 'referrals', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_referrals_to_facility'), 'referrals', ['to_facility'], unique=False)
    op.create_table('clinical_events',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('factor', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('referral_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(factor) > 0', name='ck_clinical_events_factor_nonempty'),
    sa.CheckConstraint('length(section) > 0', name='ck_clinical_events_section_nonempty'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_events_created_at'), 'clinical_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_clinical_events_created_by_user_id'), 'clinical_events', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_clinical_events_event_time'), 'clinical_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_clinical_events_factor'), 'clinical_events', ['factor'], unique=False)
    op.create_index(op.f('ix_clinical_events_id'), 'clinical_events', ['id'], unique=False)
    op.create_index(op.f('ix_clinical_events_patient_id'), 'clinical_events', ['patient_id'], unique=False)
    op.create_index('ix_clinical_events_patient_section_factor_time', 'clinical_events', ['patient_id', 'section', 'factor', 'event_time'], unique=False)
    op.create_index('ix_clinical_events_patient_time', 'clinical_events', ['patient_id', 'event_time'], unique=False)
    op.create_index(op.f('ix_clinical_events_referral_id'), 'clinical_events', ['referral_id'], unique=False)
    op.create_index(op.f('ix_clinical_events_section'), 'clinical_events', ['section'], unique=False)
    op.create_table('referral_status_history',
    sa.Column('referral_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('from_status', sa.String(length=64), nullable=True),
    sa.Column('to_status', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_name', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_status_history_actor_user_id'), 'referral_status_history', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_referral_status_history_created_at'), 'referral_status_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_referral_status_history_id'), 'referral_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_referral_status_history_kind'), 'referral_status_history', ['kind'], unique=False)
    op.create_index(op.f('ix_referral_status_history_referral_id'), 'referral_status_history', ['referral_id'], unique=False)
    op.create_index('ix_referral_status_history_referral_time', 'referral_status_history', ['referral_id', 'created_at'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_referral_status_history_referral_time', table_name='referral_status_history')
    op.drop_index(op.f('ix_referral_status_history_referral_id'), table_name='referral_status_history')
    op.drop_index(op.f('ix_referral_status_history_kind'), table_name='referral_status_history')
    op.drop_index(op.f('ix_referral_status_history_id'), table_name='referral_status_history')
    op.drop_index(op.f('ix_referral_status_history_created_at'), table_name='referral_status_history')
    op.drop_index(op.f('ix_referral_status_history_actor_user_id'), table_name='referral_status_history')
    op.drop_table('referral_status_history')
    op.drop_index(op.f('ix_clinical_events_section'), table_name='clinical_events')
    op.drop_index(op.f('ix_clinical_events_referral_id'), table_name='clinical_events')
    op.drop_index('ix_clinical_events_patient_time', table_name='clinical_events')
    op.drop_index('ix_clinical_events_patient_section_factor_time', table_name='clinical_events')
    op.drop_index(op.f('ix_clinical_events_patient_id'), table_name='clinical_events')
    op.drop_index(op.f('ix_clinical_events_id'), table_name='clinical_events')
    op.drop_index(op.f('ix_clinical_events_factor'), table_name='clinical_events')
    op.drop_index(op.f('ix_clinical_events_event_time'), table_name='clinical_events')
    op.drop_index(op.f('ix_clinical_events_created_by_user_id'), table_name='clinical_events')
    op.drop_index(op.f('ix_clinical_events_created_at'), table_name='clinical_events')
    op.drop_table('clinical_events')
    op.drop_index(op.f('ix_referrals_to_facility'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_submitted_at'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_status'), table_name='referrals')
    op.drop_index('ix_referrals_route', table_name='referrals')
    op.drop_index(op.f('ix_referrals_received_facility_status'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_received_at'), table_name='referrals')
    op.drop_index('ix_referrals_patient_status', table_name='referrals')
    op.drop_index(op.f('ix_referrals_patient_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_from_facility'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_created_by_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_created_at'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_closed_at'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_ai_patient_analyses_patient_id'), table_name='ai_patient_analyses')
    op.drop_index(op.f('ix_ai_patient_analyses_id'), table_name='ai_patient_analyses')
    op.drop_index(op.f('ix_ai_patient_analyses_created_at'), table_name='ai_patient_analyses')
    op.drop_table('ai_patient_analyses')
    op.drop_index(op.f('ix_patients_registered_facility_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_phone_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_patient_id'), table_name='patients')
    op.drop_index('ix_patients_national_id_uniqueish', table_name='patients')
    op.drop_index(op.f('ix_patients_national_id'), table_name='patients')
    op.drop_index('ix_patients_name_age', table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index('ix_patients_facility_mrn_uniqueish', table_name='patients')
    op.drop_index(op.f('ix_patients_facility_mrn'), table_name='patients')
    op.drop_index(op.f('ix_patients_district'), table_name='patients')
    op.drop_index(op.f('ix_patients_created_by_user_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_created_at'), table_name='patients')
    op.drop_index(op.f('ix_patients_age_in_years'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_time', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_approved'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_phc_facilities_name'), table_name='phc_facilities')
    op.drop_index(op.f('ix_phc_facilities_id'), table_name='phc_facilities')
    op.drop_index(op.f('ix_phc_facilities_created_at'), table_name='phc_facilities')
    op.drop_table('phc_facilities')
    op.drop_index(op.f('ix_hospital_facilities_name'), table_name='hospital_facilities')
    op.drop_index(op.f('ix_hospital_facilities_id'), table_name='hospital_facilities')
    op.drop_index(op.f('ix_hospital_facilities_created_at'), table_name='hospital_facilities')
    op.drop_table('hospital_facilities')
    # PostgreSQL keeps ENUM types after their tables are dropped; remove them for a clean downgrade
    # (no-op on SQLite, where enums are plain VARCHAR columns).
    bind = op.get_bind()
    sa.Enum(name="referral_status").drop(bind, checkfirst=True)
    sa.Enum(name="user_role").drop(bind, checkfirst=True)
