"""0003_auth_tokens_rate_limit: refresh tokens, DB-backed rate limiter, rejected registrations.

Revision ID: 0003_auth_tokens_rate_limit
Revises: 0002_facilities
Create Date: 2026-08-18

Upgrade
1. `refresh_tokens` — one row per issued refresh token: `id` Uuid PK, `user_id` FK -> users
   (ON DELETE CASCADE), `token_hash` (sha256 hex of the opaque secret, UNIQUE), `expires_at`,
   `created_at`, `revoked_at` (NULL while live), `replaced_by_id` (successor on rotation),
   `user_agent`, `ip`. See app/models/refresh_token.py, app/core/security.py.
2. `auth_rate_limit_hits` — hit log of the sliding-window rate limiter shared by every worker /
   process using the database: `id` (BIGINT on PostgreSQL, INTEGER on SQLite so it auto-increments
   there too), `key` (client IP), `hit_at`; both indexed. See app/core/rate_limit.py.
3. `users.rejected_by` (Uuid, NULL) and `users.rejected_at` (timestamptz, NULL, indexed): set by
   PATCH /admin/users/{id}/reject, cleared by approve. Added in batch mode so SQLite works.

Autogenerated against a fresh PostgreSQL 16 database at 0002_facilities and hand-checked for
portability (sa.Uuid(), variant integer PK, batch_alter_table for the users ALTERs).

Downgrade drops the two tables and the two columns (rejected users simply become plain
unapproved users again).
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003_auth_tokens_rate_limit"
down_revision: Union[str, None] = "0002_facilities"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. rate-limiter hit log -------------------------------------------------------------------
    op.create_table(
        "auth_rate_limit_hits",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("hit_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_rate_limit_hits_hit_at"), "auth_rate_limit_hits", ["hit_at"], unique=False)
    op.create_index(op.f("ix_auth_rate_limit_hits_key"), "auth_rate_limit_hits", ["key"], unique=False)

    # 2. refresh tokens -------------------------------------------------------------------------
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="fk_refresh_tokens_user_id", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refresh_tokens_expires_at"), "refresh_tokens", ["expires_at"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)

    # 3. users.rejected_by / rejected_at (batch mode: SQLite has no ALTER TABLE ... ADD INDEX) ---
    with op.batch_alter_table("users") as batch:
        batch.add_column(sa.Column("rejected_by", sa.Uuid(), nullable=True))
        batch.add_column(sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True))
        batch.create_index(op.f("ix_users_rejected_at"), ["rejected_at"], unique=False)


def downgrade() -> None:
    with op.batch_alter_table("users") as batch:
        batch.drop_index(op.f("ix_users_rejected_at"))
        batch.drop_column("rejected_at")
        batch.drop_column("rejected_by")

    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_expires_at"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")

    op.drop_index(op.f("ix_auth_rate_limit_hits_key"), table_name="auth_rate_limit_hits")
    op.drop_index(op.f("ix_auth_rate_limit_hits_hit_at"), table_name="auth_rate_limit_hits")
    op.drop_table("auth_rate_limit_hits")
